version: '3.1'

services:
  db:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: acs

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 8080:80
